### ISSUE TITLE
[Proposal] Insert a space between the "Genshin" and "Dictionary"

### ISSUE THREAD

**Issue by yasuking0304** [xicri/genshin-dictionary#239]
[Proposal]
Insert a space between the "Genshin" and "Dictionary"

https://github.com/xicri/genshin-dictionary/blob/main/layouts/default.vue#L72-L78

```scss
  &__title {
    display: flex;
    flex-wrap: wrap;
    font-weight: 300;
    font-size: 32px;
    color: vars.$color-dark;
    letter-spacing: 1px;
  }
}
```
↓
(Maybe 2px would work instead of 0.5em.)
```scss
  &__title {
    display: flex;
    flex-wrap: wrap;
    font-weight: 300;
    font-size: 32px;
    color: vars.$color-dark;
    letter-spacing: 1px;
 
    span:first-child {
      margin-right: 0.5em;
    }
  }

  &__title[href="/ja"] {
    span:first-child {
      margin-right: 0;
    }
  }
```

ScreenShot(back:now, font:after)
English
![WS000079](https://github.com/user-attachments/assets/17aa6db0-3921-4b42-80eb-76a859a179c2)

Simplified Chinese
![WS000077](https://github.com/user-attachments/assets/d05b2d43-40c3-43be-b3ff-b16882514217)

Japanese
![WS000076](https://github.com/user-attachments/assets/4357947f-3abc-4466-b5e9-c8d69e2a267c)
